project: 
  type: book
  execute-dir: file

book: 
  page-navigation: true
  title: "My GrandOrgue Implementation" 
  subtitle: "Making sense of scattered documentation and user experiences"
  site-url: "https://musicministry.github.io/grandorgue/" 
  repo-url: "https://github.com/musicministry/grandorgue"
  repo-actions: [edit, source, issue]
  favicon: assets/pipes-favicon.ico
  downloads: [pdf, docx]
  search: true
  author:
    - name: Matt Grossi
  date: today
  chapters:
    - index.qmd
    - content/hardware.qmd
    - content/setup.qmd
    - content/customizing.qmd
    # - content/rendering.qmd
    # - content/adding-refs.qmd
    - content/references.qmd

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "assets/OrganPipes.jpg"
    favicon: assets/pipes-favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://musicministry.github.io/grandorgue/
        text: "My GrandOrgue Implementation"
    style: "docked"
    search: true
    collapse-level: 1

bibliography: [content/references.bib]

execute:
  echo: false
  code-overflow: wrap

format:
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "plain"
    keep-tex: true
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: [cosmo, assets/theme.scss] 
    toc: true
    toc-depth: 3

filters:
  - assets/include-files.lua
  - quarto

# Comment next 2 lines if the PDF is having trouble
metadata-files:
  - _frontmatter.yml
 