---
title: Customization
subtitle: Using different organ sample sets
---

The default sample set is great to get started with, but it's rather small. The beauty of virtual pipe organ (VPO) software is the ability and flexibility to use any number of sample sets. [Many sample sets](https://sourceforge.net/p/ourorgan/samplesets/Sample%20Sets/) of various sizes exist, from small single-division organs to large many-division instruments. One constraint is disk storage: one needs to have enough space to download and store the sample set. The primary constraint with choosing samples to use, however, is one's memory: the sample set must fit in the computer's RAM to work properly. Thus, my constraint was 16 GB RAM that came on the Raspberry Pi 5. What this means in practice:

- **Under 8 GB:** loads comfortably, plenty of headroom
- **8–14 GB:** should work fine, some breathing room for OS
- **14-15 GB** getting risky; the OS and GrandOrgue itself need some RAM too, so you don't want to use all 16 GB for the sample set
- **Over 15 GB:** will not work; not enough memory for GrandOrgue and the OS

Since I only had one keyboard with no pedalboard, it made sense to consider single-manual samples. I could use larger ones, but I could only play one manual. The workaround would be mapping the Great division to my keyboard and relying on couplers to play other manuals from the Great manual.

## Bureå Funeral Chapel

The first organ I tried was the [Bureå Funeral Chapel](https://familjenpalo.se/vpo/download/) from [Lars Virtual Pipe Organs](https://familjenpalo.se/vpo/). This is a small chamber organ with one manual, pedals, and 9 stops. All of the manual stops are split stops with separate drawknobs for bass (first two octaves) and division. This provides greater flexibility on a small instrument, allowing the organist to use different combinations of stops on one manual instead of across two manuals.

First, I [downloaded the `.rar`](https://familjenpalo.se/vpo/download/) file. I needed to install the "unrar" utility the first time in order to extract this:

```bash
sudo apt install unrar
```

Then I unpacked it into the `GrandOrgue/Organs/` directory:

```bash
unrar x Burea_Funeral_Chapel.rar /home/username/GrandOrgue/Organs/Burea_Funeral_Chapel/
```

Open GrandOrgue, then got to File → Open, find and select the desired organ sample, and click "Open". If everything worked, the new organ should load and be ready for use.

