---
title: Hardware
subtitle: Requirements and considerations
---

## BLUF

The minimum requirements needed to get started with GrandOrgue are:

* Computer with at least 8 GB RAM (16+ GB preferred)
* Touch screen monitor (for interacting with virtual console controls)
* MIDI-USB cable or MIDI cable with a USB audio interface device for connecting the computer to the MIDI instrument
* MIDI-ready organ or keyboard

And, if you  don't want the sound to play from your computer speakers:

* Audio cable to port audio from computer to an organ amplifier  
  *or*  
* Quality external speakers to connect directly to the computer

## Discussion

[GrandOrgue](https://github.com/GrandOrgue/grandorgue) is free open source computer software supported for Windows, MacOS, and at least some Linux distributions. System and hardware requirements are summarized [here](https://grandorgue.com/), with the most important requirement being **RAM**.

My initial installation was intended to proof-of-concept learning experiment to assess whether or not it was something I wanted to delve further into and scale up. I already had an old (circa 1997) Casio MIDI keyboard[^1], so I decided to use that as the workbench test case for experimentation. Then, once I knew what I was doing and felt comfortable with the technical components, I wanted to transfer the setup to a MIDI-ready digital church organ to try it out "in the field" with an actual organ console, decent speakers, and a room where an organ is regularly used.

[^1]: Old keyboards can almost always be found on Facebook Marketplace or similar sites for free or very little money. Just make sure it supports MIDI, which most manufactured after the 1980s will.

With this in mind, I sought portability with minimal spatial footprint. Desktop computers took up too much space and are not easily portable, so they were out. Without having a personal organ at home, I needed to interface with the software directly through the computer rather than via an organ console, so I wanted to have a touch screen monitor that could be positioned in close proximity to the music keyboard. While standard laptops with touch screens are portable and could work, I would have to always reach over the laptop keyboard to reach the screen, which was not ideal. My solution was to use a [**Raspberry Pi**](https://www.raspberrypi.com/) together with a simple **touch screen monitor**.

I opted for the [Raspberry Pi 5](https://www.raspberrypi.com/products/raspberry-pi-5/) because it was the first and, as of 2026, only unit to support 16 GB of RAM. I purchased a full starter kit for $385 which included:

* Raspberry Pi 5 with 2.4Ghz 64-bit quad-core CPU and 64 GB of RAM
* 128GB Micro SD Card pre-loaded with 64-bit Raspberry Pi OS, USB MicroSD Card Reader
* Plastic protective case
* Low noise bearing system fan
* Heat sink
* 45W PD Power Supply
* 2 6-foot display cables

I bought a simple and compact [15.6" portable touch screen monitor](https://www.amazon.com/dp/B0BPX1QSLV?ref=ppx_yo2ov_dt_b_fed_asin_title) for $95 as my primary means of interacting with GrandOrgue. An upgrade might be in store down the road, but this will due to start.

Unfortunately, the Raspberry Pi 5 does not have a dedicated 3.5mm headphone audio jack like its predecessor. Audio is outputted through HDMI or USB instead. I ended up buying a [Behringer UMC204HD](https://www.amazon.com/dp/B00QHURLCW) **USB audio interface** for $116 which would allow me to use a single USB port for both audio and to connect standard MIDI cables instead of a MIDI-USB cable. I also bought a 9.8-foot dual 5-pin **MIDI cable** for $11 to go along with that because I did not have one already.

Altogether, my expenses for the initial set up came out to be just over $600:

Expense                  | Cost (USD) 
:------------------------|:----------:
Raspberry Pi 5 kit       | $385
Behringer UMC204HD       | $116
Touch screen monitor     | $95
MIDI cable               | $11
Keyboard                 | $0
**TOTAL**                | **$607**
: Total cost of my initial proof-of-concept setup.

Not bad for an authentic-sounding practice organ! The pages that follow describe how I set up, configured, and tested everything.